/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [];
    "ignition.healthCheck": [];
    "ignition.executeSolution": [];
    "ignition.updateConfig": [];
    "locale.update": [];
    "home": [];
    "dashboard": [];
    "faqs": [];
    "users.index": [];
    "users.create": [];
    "users.store": [];
    "users.edit": [
      {
        "name": "user";
        "required": true;
        "binding": "id";
      }
    ];
    "users.edit.password": [
      {
        "name": "user";
        "required": true;
        "binding": "id";
      }
    ];
    "users.update": [
      {
        "name": "user";
        "required": true;
        "binding": "id";
      }
    ];
    "users.destroy": [
      {
        "name": "user";
        "required": true;
        "binding": "id";
      }
    ];
    "roles.index": [];
    "roles.store": [];
    "roles.update": [
      {
        "name": "role";
        "required": true;
        "binding": "id";
      }
    ];
    "roles.destroy": [
      {
        "name": "role";
        "required": true;
        "binding": "id";
      }
    ];
    "permissions.index": [];
    "permissions.store": [];
    "permissions.update": [
      {
        "name": "permission";
        "required": true;
        "binding": "id";
      }
    ];
    "permissions.destroy": [
      {
        "name": "permission";
        "required": true;
        "binding": "id";
      }
    ];
    "projects.index": [];
    "projects.create": [];
    "projects.store": [];
    "projects.show": [
      {
        "name": "project";
        "required": true;
        "binding": "ulid";
      }
    ];
    'projects_admin.show': {
      uri: 'admin/projects/{status}/{project}',
      methods: ['GET', 'HEAD'],
      parameters: ['status', 'project'],
      bindings: { project: 'ulid' },
    },
    "pos.show": [
      {
        "name": "project";
        "required": true;
      }
    ];
    "projects_moderation.index": [];
    "projects_rejected.index": [];
    "projects_active.index": [];
    "projects.moderate": [
      {
        "name": "project";
        "required": true;
        "binding": "ulid";
      }
    ];
    "register": [];
    "login": [];
    "password.request": [];
    "password.email": [];
    "password.reset": [
      {
        "name": "token";
        "required": true;
      }
    ];
    "password.store": [];
    "verification.notice": [];
    "verification.verify": [
      {
        "name": "id";
        "required": true;
      },
      {
        "name": "hash";
        "required": true;
      }
    ];
    "verification.send": [];
    "password.confirm": [];
    "password.update": [];
    "logout": [];
  }
}
export {};
